apiVersion: v1
kind: ConfigMap  # It's not a secrets resource because it's just a local testing environment.
metadata:
  namespace: main-project
  name: backend-secrets
data:
  NODE_ENV: development
  SERVER_PORT: "5000"
  SITE_URL: "http://localhost:5000/"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/stunning-journey"
  ACCESS_TOKEN_SECRET: triplej
  JWT_PRIVATE_KEY: justanotherprivatekey
  JWT_PUBLIC_KEY: notimportant
  JWT_ALGORITHM: HS256
  JWT_EXPIRE_TIME: "2592000"
  JWT_EXPIRE_REFRESH_TIME: "2592000"
  SALT_ROUNDS: "10"
  GRAPHQL_PLAYGROUND: "true"
  LIBERA_EMAIL_ACCOUNT: librera.emailing@gmail.com
  SECRET_COOKIE_PASSWORD: "vDWwLoNCs2xCGB4QFBtyPvkX3jJiEX69"
  MOOSEND_API_KEY: "70e6d5ab-3e1e-4b5a-bab1-06772c572d1f"
  NODEMAILER_PASSWORD: "ulpqodtmytpiwtih"
