apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-project
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: jfer11/thesis-frontend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          command: ["npm","run","start"]
          # envFrom:
          #   - configMapRef:
          #       name: frontend-secret

---
apiVersion: v1
kind: Service
metadata:
  namespace: main-project
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3000
      nodePort: 30002
  selector:
    app: nextjs
