apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-aws-cli
  namespace: main-project
spec:
  selector:
    matchLabels:
      app: demo-aws-cli
  template:
    metadata:
      labels:
        app: demo-aws-cli
    spec:
      serviceAccountName: s3-access
      containers:
      - name: demo-aws-cli
        image: amazon/aws-cli
        command: ['sh', '-c']
        args:
        - |
          echo "This is a NEW dummy file." > /dummy.txt && \
          aws s3 cp /dummy.txt s3://libera-bucket/dummy.txt --acl public-read
