kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: main-project
  name: postgres-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-pv
