apiVersion: v1
kind: ConfigMap
metadata:
  namespace: main-project
  name: backend-config-map
data:
  # Generals
  NODE_ENV: production
  SERVER_PORT: "5000"
  SITE_URL: "http://localhost:5000/"  # This must match SERVER_PORT.
  # Database
  DATABASE_URL: "postgresql://liberadbusername:bNw6Z7IWsIQK3dnv@libera-postgresql.cp3bickqbfzo.us-east-1.rds.amazonaws.com:5432/liberadbname?schema=pubilc"  # TODO: Change this
  DATABASE_NAME: liberadbname
  # Jwt options
  JWT_ALGORITHM: HS256
  JWT_EXPIRE_TIME: "2592000"
  JWT_EXPIRE_REFRESH_TIME: "2592000"
  SALT_ROUNDS: "10"
  # Graphql options
  GRAPHQL_PLAYGROUND: "true"
  # Nodemailer
  LIBERA_EMAIL_ACCOUNT: librera.emailing@gmail.com
