apiVersion: v1
kind: ConfigMap
metadata:
  namespace: main-project
  name: backend-config-map
data:
  NODE_ENV: production
  SERVER_PORT: "5000"
  SITE_URL: "http://localhost:5000/"  # This must match SERVER_PORT.
  DATABASE_URL: "postgresql://liberadbusername:bNw6Z7IWsIQK3dnv@postgres-service:5432/liberadbname"
  JWT_ALGORITHM: HS256
  JWT_EXPIRE_TIME: "2592000"
  JWT_EXPIRE_REFRESH_TIME: "2592000"
  SALT_ROUNDS: "10"
  GRAPHQL_PLAYGROUND: "true"
  LIBERA_EMAIL_ACCOUNT: librera.emailing@gmail.com
