apiVersion: v1
kind: ConfigMap
metadata:
  namespace: main-project
  name: frontend-config-map
data:
  SERVER_API_URL: http://localhost:5001/graphql  # TODO: Change this
  NEXT_PUBLIC_API_URL: http://localhost:5001/graphql  # TODO: Change this
  ENV: production
  NEXT_PUBLIC_ENV: production
