# Use secrets for things which are actually secret like API keys, credentials, etc
# Base64 encode the values stored in a Kubernetes Secret: $ pbpaste | base64 | pbcopy
# The --decode flag is convenient: $ pbpaste | base64 --decode
# Ex:
# echo -n 'admin' | base64
# YWRtaW4=

apiVersion: v1
kind: Secret
metadata:
  namespace: main-project
  name: backend-secrets
type: Opaque
data:
  SECRET_COOKIE_PASSWORD: dkRXd0xvTkNzMnhDR0I0UUZCdHlQdmtYM2pKaUVYNjk=
  ACCESS_TOKEN_SECRET: dHJpcGxlag==
  JWT_PRIVATE_KEY: anVzdGFub3RoZXJwcml2YXRla2V5
  JWT_PUBLIC_KEY: bm90aW1wb3J0YW50
  MOOSEND_API_KEY: NzBlNmQ1YWItM2UxZS00YjVhLWJhYjEtMDY3NzJjNTcyZDFm
  NODEMAILER_PASSWORD: dWxwcW9kdG15dHBpd3RpaA==
  # ver imagePullSecrets
  