# Use secrets for things which are actually secret like API keys, credentials, etc
# Base64 encode the values stored in a Kubernetes Secret: $ pbpaste | base64 | pbcopy
# The --decode flag is convenient: $ pbpaste | base64 --decode
# Ex:
# echo -n 'admin' | base64
# YWRtaW4=

apiVersion: v1
kind: Secret
metadata:
  namespace: main-project
  name: frontend-secrets
type: Opaque
data:
  SECRET_COOKIE_PASSWORD: dkRXd0xvTkNzMnhDR0I0UUZCdHlQdmtYM2pKaUVYNjk=
