apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main-project
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: jfer11/thesis-backend:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["sleep 5; echo 4HOLAADIUUSIUUA44 && npm ci --ignore-script=prepare && echo EREI && prisma generate && prisma migrate deploy && npm start"]
          envFrom:
          - configMapRef:
              name: backend-config-map
          - secretRef:
              name: backend-secrets

---
apiVersion: v1
kind: Service
metadata:
  namespace: main-project
  name: backend-service
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5000
  selector:
    app: nestjs
